### ISSUE TITLE
Unable to perform OCR

### ISSUE THREAD

**Issue by ivnc** [ruifontes/tesseractOCR#5]
A Spanish-speaking user has reached us with a problem performing OCR with TesseractOCR.
When trying to scan from a physical scanner, the add-on keeps beeping indeffinitely, and when trying to scan a JPG/PNG file it says "Processing, please wait. This operation can take some seconds" and nothing happens. It is reproducible with any image file and with any add-on version, including those previous to code rewrite.
[NVDA debug log](https://github.com/ruifontes/tesseractOCR/files/9413667/registro.NVDA_TesseractOCR-censurado.txt)
**CENSORED** is the user's Windows username, compound by two words separated by an space, p.ex. "Juan Perez" (no special characters).

**Comment by ruifontes** [comment]
Today, 05/05/23, will be released a new version.
If  think the problem was the user name, and if so, it is solved.

**Comment by ivnc** [comment]
The user confirms that the issue is fixed, but only after installing NVDA 2023.1. Fyi.

**Comment by ruifontes** [comment]
Good!
