### ISSUE TITLE
Issue with config and files

### ISSUE THREAD

**Issue by CyrilleB79** [ruifontes/tesseractOCR#8]
Hi Rui

!There seem to be issues with config and files.

### Log error
When trying to recognize a file:
```
ERROR - stderr (13:57:04.178) - Thread-16 (2908):
Exception in thread Thread-16:
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\tesseractOCR\globalPlugins\tesseractOCR\__init__.py", line 259, in doRoutines1
    self.OCR_image_files(docPath)
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\tesseractOCR\globalPlugins\tesseractOCR\__init__.py", line 195, in OCR_image_files
    self.creatTXTFromVariousTXT()
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\tesseractOCR\globalPlugins\tesseractOCR\__init__.py", line 202, in creatTXTFromVariousTXT
    self.showResults()
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\tesseractOCR\globalPlugins\tesseractOCR\__init__.py", line 232, in showResults
    with open(os.path.join(PLUGIN_DIR, "images", "ocr.txt"), "r", encoding = "utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\CB232690\\AppData\\Roaming\\nvda\\addons\\tesseractOCR\\globalPlugins\\tesseractOCR\\images\\ocr.txt'

```

### Note
I cannot remember exactly what I did to go to this point. I have tried to add and remove various languages. But it may be linked to the following points:
1. I may have modified the options (added or removed languages) but do not save automatically the configuration when exiting NVDA. Is it a supported case? Maybe I have a language list in the config that differs from the language data files?
2. I may have modified the options (added/removed languages) while in a profile instead of in the default profile. Is it supported? If no, you should ensure that only the default config is changed, not the profile config.

### PS (off-topic)
I won't open an issue for it. But could you remove the message "No WIA device available" when NVDA starts? It's useless to hear it at each startup for someone who does not have a scanner. You may want to report this message when calling the command capturing the text from the scanner.

**Comment by ruifontes** [comment]
Regarding the offtopic PS: It is already fixed.

**Comment by ruifontes** [comment]
Regarding the log error, it was with version 2023.05.05?

**Comment by ruifontes** [comment]
Regarding the note, what I want is have the tesseractOCR configuration section present in all profiles, but saved only on the default profile...
How to manage that?

**Comment by CyrilleB79** [comment]
> Regarding the log error, it was with version 2023.05.05?

Yes, the one you sent me in the drive link in #7 . Sorry, I had forgotten to mention it.

> Regarding the note, what I want is have the tesseractOCR configuration section present in all profiles, but saved only on the default profile... How to manage that?

No idea at all. You may ask on the add-on mailing list if an add-on dev has an idea.

**Comment by ruifontes** [comment]
Fixed and closed.
